
// This file was auto-generated by ML.NET Model Builder. 

using System;

namespace MLModel_ConsoleApp
{
    class Program
    {
        static void Main(string[] args)
        {
            // Create single instance of sample data from first line of dataset for model input
            MLModel.ModelInput sampleData = new MLModel.ModelInput()
            {
                Rate_code = 1F,
                Passenger_count = 1F,
                Trip_time_in_secs = 1271F,
                Trip_distance = 3.8F,
                Payment_type = @"CRD",
                Fare_amount = 17.5F,
            };

            // Make a single prediction on the sample data and print results
            var predictionResult = MLModel.Predict(sampleData);

            Console.WriteLine("Using model to make single prediction -- Comparing actual Vendor_id with predicted Vendor_id from sample data...\n\n");


            Console.WriteLine($"Vendor_id: {@"CMT"}");
            Console.WriteLine($"Rate_code: {1F}");
            Console.WriteLine($"Passenger_count: {1F}");
            Console.WriteLine($"Trip_time_in_secs: {1271F}");
            Console.WriteLine($"Trip_distance: {3.8F}");
            Console.WriteLine($"Payment_type: {@"CRD"}");
            Console.WriteLine($"Fare_amount: {17.5F}");


            Console.WriteLine($"\n\nPredicted Vendor_id: {predictionResult.Prediction}\n\n");
            Console.WriteLine("=============== End of process, hit any key to finish ===============");
            Console.ReadKey();
        }
    }
}
